name: es_tripadvisor_nyc
channels:
  - conda-forge
dependencies:
  - python=3.10
  - elasticsearch
  - eland=8.12.1
  - celery
  - ipykernel
  - pip
  - langchain
  - streamlit
  - streamlit-chat
  - nltk
  - pip:
    - openai
    - eland[pytorch]
